server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/sicc-msa-poc/spring_cloud_config_repository
          search-paths: apple, banana
          username: sicc-msa-poc
          password: siccmsapoc201905! 

