server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/cjk5586/configRepository.gitd
          search-paths: apple, banana
          username: cjk5586
          password: vision2017#  

