# TODO S1-10-2-1 서버포트, 어플리케이션명 설정, 대시보드를 위한 freemaker path 설정
server:
  port: 8092

spring:
  application:
    name: EurekaServer

  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

# TODO S1-10-2-1 eureka 관련 설정
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/