server:
  port: 8082
  
spring:
  application:
    name: work
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true

# hystrix dashborad 가시화를 위한 설정
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

# eureka client 관련 설정
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true