server:
  port: 8082
  
spring:
  application:
    name: work
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true

# TODO S1-7-6-5 hystrix dashborad 가시화를 위한 설정
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"