# 서버 포트
server:
  port: 8084

# 어플리케이션명  
spring:
  application:
    name: work_copied_2
# datasource 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
# h2 콘솔 사용 여부
  h2:
    console:
      enabled: true

# hystrix dashborad 가시화를 위한 설정
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

# logging level을 web에 관련하여 DEBUG까지
logging:
  level:
    com:
      sicc:
        work:
          api: DEBUG