server:
  port: 8081  
spring:  application:    name: member
  datasource:    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:    console:      enabled: true
# sleuth 설정
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
# zipkin server 연결
  zipkin:    base-url: http://127.0.0.1:9411/
    enabled: true
# zipkin sample
sample:
  zipkin:
    enabled: true
# logging 레벨 설정
logging:
  level:
    org:
      springframework:
        web: DEBUG