server:
  port: 8081
  
spring:  application:    name: member
  datasource:    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:    console:      enabled: true

# TODO S1-4-6-1 hystrix timeout (기본 1초 -> 10초)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
